package com.acework.shabaretailer.atlas

import com.acework.shabaretailer.model.Item

const val STATE_LOADING = 0
const val STATE_SUCCESS = 1
const val STATE_ERROR = 2

const val PRICE_WAHURA = 35
const val PRICE_TWENDE = 25

val items = hashMapOf(
    "1" to Item(
        color = "Cream",
        description = "Twende sling bag is a mini pouch that comes with an adjustable strap and a detachable insert. The earth tone colours highlight our artisan skill, a heritage craft passed down through generations. The bag features a draw string for closure. It can be worn as a sling bag or a cross body bag. This is your on the go bag for a weekend hangout, quick run around town and can be your statement adventure bag for your next holiday destination as you explore the beach or safari. It perfectly fits your essentials like your passport & phone with extra space for your go to lipstick and small carriables.",
        features = listOf(
            "Adjustable strap",
            "Draw-string top closure",
            "Handmade in Kenya"
        ),
        insert = "Poly-cotton material",
        material = "Sisal",
        name = "Twende Sling Bag",
        price = PRICE_TWENDE,
        size = "15cm height, 11cm width",
        sku = "1",
        strap = "100% leather, brown",
        strapLength = "60cm, adjustable",
        type = "Mini pouch",
        weaving = "Micro-woven",
        weight = 213
    ),
    "3" to Item(
        color = "Cream",
        description = "Wahura bucket bag is definitely a fashion statement, The bucket bag doubles in style and functionality, can be worn during the day and smoothly transitions into an evening bag. This bag can be worn as a shoulder bag as well as a wrist bag not to mention that the insert comes with an inside pocket for easy organisation. Its definitely the perfect finish to elevate your style.",
        features = listOf(
            "25cm strap drop",
            "Adjustable strap",
            "Draw-string top closure",
            "Handmade in Kenya",
            "Inner pocket"
        ),
        insert = "Poly-cotton material",
        material = "Sisal",
        name = "Wahura Bucket Bag",
        price = PRICE_WAHURA,
        size = "-",
        sku = "3",
        strap = "100% leather, brown",
        strapLength = "60cm, adjustable",
        type = "Bucket bag",
        weaving = "Micro-woven",
        weight = 424
    )
)

val countriesWithCodes = mapOf(
    "Afghanistan" to "AF",
    "Aland Islands" to "AX",
    "Albania" to "AL",
    "Algeria" to "DZ",
    "American Samoa" to "AS",
    "Andorra" to "AD",
    "Angola" to "AO",
    "Anguilla" to "AI",
    "Antarctica" to "AQ",
    "Antigua and Barbuda" to "AG",
    "Argentina" to "AR",
    "Armenia" to "AM",
    "Aruba" to "AW",
    "Australia" to "AU",
    "Austria" to "AT",
    "Azerbaijan" to "AZ",
    "Bahamas" to "BS",
    "Bahrain" to "BH",
    "Bangladesh" to "BD",
    "Barbados" to "BB",
    "Belarus" to "BY",
    "Belgium" to "BE",
    "Belize" to "BZ",
    "Benin" to "BJ",
    "Bermuda" to "BM",
    "Bhutan" to "BT",
    "Bolivia" to "BO",
    "Bonaire, Sint Eustatius and Saba" to "BQ",
    "Bosnia and Herzegovina" to "BH",
    "Botswana" to "BW",
    "Brazil" to "BR",
    "British Indian Ocean Territory" to "IO",
    "Brunei" to "BN",
    "Bulgaria" to "BG",
    "Burkina Faso" to "BF",
    "Burundi" to "BI",
    "Cambodia" to "KH",
    "Cameroon" to "CM",
    "Canada" to "CA",
    "Cape Verde" to "CV",
    "Cayman Islands" to "KY",
    "Central African Republic" to "CF",
    "Chad" to "TD",
    "Chile" to "CL",
    "China" to "CN",
    "Christmas Island" to "CX",
    "Cocos (Keeling) Islands" to "CC",
    "Colombia" to "CO",
    "Comoros" to "KM",
    "Congo (the Democratic Republic of)" to "CD",
    "Congo (the)" to "CG",
    "Cook Islands" to "CK",
    "Costa Rica" to "CR",
    "Croatia" to "HR",
    "Cuba" to "CU",
    "Curacao" to "CW",
    "Cyprus" to "CY",
    "Czech Republic" to "CZ",
    "Cote d'Ivoire" to "CI",
    "Denmark" to "DK",
    "Djibouti" to "DJ",
    "Dominica" to "DM",
    "Dominican Republic" to "DO",
    "Ecuador" to "EC",
    "Egypt" to "EG",
    "El Salvador" to "SV",
    "Equatorial Guinea" to "GQ",
    "Eritrea" to "ER",
    "Estonia" to "EE",
    "Eswatini" to "SZ",
    "Ethiopia" to "ET",
    "Falkland Islands" to "FK",
    "Faroe Islands" to "FO",
    "Fiji" to "FJ",
    "Finland" to "FI",
    "France" to "FR",
    "French Guiana" to "GF",
    "French Polynesia" to "PF",
    "French Southern Territories" to "TF",
    "Gabon" to "GA",
    "Gambia" to "GM",
    "Georgia" to "GE",
    "Germany" to "DE",
    "Ghana" to "GH",
    "Gibraltar" to "GI",
    "Greece" to "GR",
    "Greenland" to "GL",
    "Grenada" to "GD",
    "Guadeloupe" to "GP",
    "Guam" to "GU",
    "Guatemala" to "GT",
    "Guernsey" to "GG",
    "Guinea" to "GN",
    "Guinea-Bissau" to "GW",
    "Guyana" to "GY",
    "Haiti" to "HT",
    "Honduras" to "HN",
    "Hong Kong" to "HK",
    "Hungary" to "HU",
    "Iceland" to "IS",
    "India" to "IN",
    "Indonesia" to "ID",
    "Iran" to "IR",
    "Iraq" to "IQ",
    "Ireland" to "IE",
    "Isle of Man" to "IM",
    "Israel" to "IL",
    "Italy" to "IT",
    "Jamaica" to "JM",
    "Japan" to "JP",
    "Jersey" to "JE",
    "Jordan" to "JO",
    "Kazakhstan" to "KZ",
    "Kenya" to "KE",
    "Kiribati" to "KI",
    "Korea (the Democratic People's Republic of)" to "KP",
    "Korea (the Republic of)" to "KR",
    "Kuwait" to "KW",
    "Kyrgyzstan" to "KG",
    "Laos" to "LA",
    "Latvia" to "LV",
    "Lebanon" to "LB",
    "Lesotho" to "LS",
    "Liberia" to "LR",
    "Libya" to "LY",
    "Liechtenstein" to "LI",
    "Lithuania" to "LT",
    "Luxembourg" to "LU",
    "Macao" to "MO",
    "Madagascar" to "MG",
    "Malawi" to "MW",
    "Malaysia" to "MY",
    "Maldives" to "MV",
    "Mali" to "ML",
    "Malta" to "MT",
    "Marshall Islands" to "MH",
    "Martinique" to "MQ",
    "Mauritania" to "MR",
    "Mauritius" to "MU",
    "Mayotte" to "YT",
    "Mexico" to "MX",
    "Micronesia" to "FM",
    "Moldova" to "MD",
    "Monaco" to "MC",
    "Mongolia" to "MN",
    "Montenegro" to "ME",
    "Montserrat" to "MS",
    "Morocco" to "MA",
    "Mozambique" to "MZ",
    "Myanmar" to "MM",
    "Namibia" to "NA",
    "Nauru" to "NR",
    "Nepal" to "NP",
    "Netherlands" to "NL",
    "New Caledonia" to "NC",
    "New Zealand" to "NZ",
    "Nicaragua" to "NI",
    "Niger" to "NE",
    "Nigeria" to "NG",
    "Niue" to "NU",
    "Norfolk Island" to "NF",
    "North Macedonia" to "MK",
    "Northern Mariana Islands" to "MP",
    "Norway" to "NO",
    "Oman" to "OM",
    "Pakistan" to "PK",
    "Palau" to "PW",
    "Panama" to "PA",
    "Papua New Guinea" to "PG",
    "Paraguay" to "PY",
    "Peru" to "PE",
    "Philippines" to "PH",
    "Pitcairn" to "PN",
    "Poland" to "PL",
    "Portugal" to "PT",
    "Puerto Rico" to "PR",
    "Qatar" to "QA",
    "Reunion" to "RE",
    "Romania" to "RO",
    "Russian Federation" to "RU",
    "Rwanda" to "RW",
    "Saint-Barthelemy" to "BL",
    "Saint Helena" to "SH",
    "Saint Kitts and Nevis" to "KN",
    "Saint Lucia" to "LC",
    "Saint Martin (French part)" to "MF",
    "Saint Pierre and Miquelon" to "PM",
    "Saint Vincent and the Grenadines" to "VC",
    "Samoa" to "WS",
    "San Marino" to "SM",
    "Sao Tome and Principe" to "ST",
    "Saudi Arabia" to "SA",
    "Senegal" to "SN",
    "Serbia" to "RS",
    "Seychelles" to "SC",
    "Sierra Leone" to "SL",
    "Singapore" to "SG",
    "Sint Maarten (Dutch part)" to "SX",
    "Slovakia" to "SK",
    "Slovenia" to "SI",
    "Solomon Islands" to "SB",
    "Somalia" to "SO",
    "South Africa" to "ZA",
    "South Georgia and the South Sandwich Islands" to "GS",
    "South Sudan" to "SS",
    "Spain" to "ES",
    "Sri Lanka" to "SL",
    "Sudan" to "SD",
    "Suriname" to "SR",
    "Svalbard and Jan Mayen" to "SJ",
    "Sweden" to "SE",
    "Switzerland" to "CH",
    "Syria" to "SY",
    "Taiwan" to "TW",
    "Tajikistan" to "TJ",
    "Tanzania" to "TZ",
    "Thailand" to "TH",
    "Timor-Leste" to "TL",
    "Togo" to "TG",
    "Tokelau" to "TK",
    "Tonga" to "TO",
    "Trinidad and Tobago" to "TT",
    "Tunisia" to "TN",
    "Turkey" to "TR",
    "Turkmenistan" to "TM",
    "Turks and Caicos Islands" to "TC",
    "Tuvalu" to "TV",
    "Uganda" to "UG",
    "Ukraine" to "UA",
    "United Arab Emirates" to "AE",
    "United Kingdom" to "GB",
    "United States" to "US",
    "United States Minor Outlying Islands" to "UM",
    "Uruguay" to "UY",
    "Uzbekistan" to "UZ",
    "Vanuatu" to "VU",
    "Vatican City State" to "",
    "Venezuela" to "VE",
    "Vietnam" to "VN",
    "Virgin Islands (British)" to "VG",
    "Virgin Islands (U.S.)" to "VI",
    "Wallis and Futuna" to "WF",
    "Western Sahara" to "EH",
    "Yemen" to "YE",
    "Zambia" to "ZM",
    "Zimbabwe" to "ZW"
)